language: generic

sudo: required

dist: trusty

services:
  - docker

install:
  - sudo apt-get update -y && sudo apt-get install -y html2text
  - docker pull lamtev/java
  - docker pull lamtev/latex

script:
  - docker run -v $TRAVIS_BUILD_DIR:/notation_translation lamtev/java /bin/bash -c " cd notation_translation && gradle build "
  - html2text ${TRAVIS_BUILD_DIR}/core/build/reports/tests/classes/com.lamtev.notation_translator.core.StringCompilerTest.html
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/cli/build/distributions/cli-1.0-SNAPSHOT.tar
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/cli/build/distributions/cli-1.0-SNAPSHOT.zip
  - docker run -v $TRAVIS_BUILD_DIR:/notation_translation lamtev/latex /bin/bash -c " cd notation_translation/report && pdflatex report.tex && pdflatex report.tex "
  - sudo chmod 777 ${TRAVIS_BUILD_DIR}/report/report.pdf

after_success:
  - sudo bash <(curl -s https://codecov.io/bash)
  
deploy:
  provider: releases
  api_key: "$GITHUB_DEPLOY_TOKEN"
  file: 
    - ${TRAVIS_BUILD_DIR}/cli/build/distributions/cli-1.0-SNAPSHOT.tar
    - ${TRAVIS_BUILD_DIR}/cli/build/distributions/cli-1.0-SNAPSHOT.zip
    - ${TRAVIS_BUILD_DIR}/report/report.pdf
  skip_cleanup: true
  on:
    tags: true
